name: clean_lock
version: 0.0.8
author: Clean Team <clean@vacuumlabs.com>
description: Locking server
homepage: https://github.com/cleandart/clean_lock
dependencies:
  clean_logging: '>=0.4.1'
  unittest: any
  useful: '>=1.0.18 <2.0.0'
